### ISSUE TITLE
yarn 安装包的时候，提示需要访问github

### ISSUE THREAD

**Issue by hongyin163** [Chimeejs/chimee#241]
我在公司的构建环境里构建，构建不能访问github，现在提示
`
Output:

fatal: unable to access 'https://github.com/Chimeejs/chimee-helper.git/': SSL connect error

at ProcessTermError.ExtendableBuiltin (/root/nvm/versions/node/v8.11.4/lib/node_modules/yarn/lib/cli.js:721:66)

at ProcessTermError.MessageError (/root/nvm/versions/node/v8.11.4/lib/node_modules/yarn/lib/cli.js:750:123)

at new ProcessTermError (/root/nvm/versions/node/v8.11.4/lib/node_modules/yarn/lib/cli.js:790:113) 
`
安装chimee-helper为什么要访问github库？帮忙看下，谢谢！

**Comment by toxic-johann** [comment]
应该是某些库在依赖上指定了这个库的 github 版本。
